FROM postgres

RUN pip install Flask
ADD . /code
WORKDIR /code
CMD python app.py


	# in dockerfile: from postgres,
					 install psycogp2, python 2.7
					 run two scripts
					 CMD: postgres (start postgres)

					 # slack michael and show him my repo
					 # jonathan told me you might be able to help

					 # each one indep works, can't get the two to talk together